# Generated by Django 2.2.10 on 2020-07-28 08:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название опроса')),
                ('date_start', models.DateField(auto_now_add=True, verbose_name='Дата начала опроса')),
                ('date_end', models.DateField(null=True, verbose_name='Дата окончания опроса')),
                ('description', models.CharField(max_length=1500, verbose_name='Описание опроса')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'db_table': 'interviews',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Текст вопроса')),
                ('type_question', models.SmallIntegerField(choices=[(0, 'Ответ с текстом'), (1, 'Ответ с выбором одного варианта'), (2, 'Ответ с выбором нескольких вариантов')], default=0, verbose_name='Тип ответа')),
                ('text_for_answer', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, verbose_name='Ответ с выбором вариантов ответа'), blank=True, default=list, size=None)),
                ('interview', models.ManyToManyField(related_name='questions', to='interview_main.Interview', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(verbose_name='ID пользователя')),
                ('type_answer', models.SmallIntegerField(choices=[(0, 'Ответ с текстом'), (1, 'Ответ с выбором одного варианта'), (2, 'Ответ с выбором нескольких вариантов')], default=0, verbose_name='Тип ответа')),
                ('answer', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, verbose_name='Ответ текстом/с выбором одного варианта'), blank=True, default=list, size=1)),
                ('multiple_choice_answer', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, verbose_name='Ответ с выбором нескольких вариантов'), blank=True, default=list, size=None)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interview_main.Question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'db_table': 'answers',
            },
        ),
    ]
